# Generated by Django 5.2.4 on 2025-09-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tafzily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tafzilycode', models.CharField(max_length=20, unique=True)),
                ('subscription', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=10)),
                ('fname', models.CharField(max_length=100)),
                ('lastname', models.CharField(blank=True, max_length=100, null=True)),
                ('nationalID', models.CharField(blank=True, max_length=20, null=True)),
                ('postalCode', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('economicID', models.CharField(blank=True, max_length=50, null=True)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('tel', models.CharField(blank=True, max_length=20, null=True)),
                ('selectedOptions', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('bad', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('change', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('mandeh', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('ozv', models.BooleanField(default=False)),
                ('atbarok', models.BooleanField(default=False)),
                ('atbar', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('moen_name', models.CharField(blank=True, max_length=255, null=True)),
                ('daftar', models.CharField(blank=True, max_length=50, null=True)),
                ('moarref', models.CharField(blank=True, max_length=255, null=True)),
                ('sms', models.CharField(blank=True, max_length=50, null=True)),
                ('ashxas', models.CharField(blank=True, max_length=255, null=True)),
                ('tafzily_sharh', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
