# Generated by Django 5.2.4 on 2025-09-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tafzili', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tafzily',
            options={'managed': True},
        ),
        migrations.RemoveField(
            model_name='tafzily',
            name='address',
        ),
        migrations.RemoveField(
            model_name='tafzily',
            name='atbarok',
        ),
        migrations.RemoveField(
            model_name='tafzily',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='tafzily',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tafzily',
            name='economicID',
        ),
        migrations.RemoveField(
            model_name='tafzily',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='tafzily',
            name='moen_name',
        ),
        migrations.RemoveField(
            model_name='tafzily',
            name='nationalID',
        ),
        migrations.RemoveField(
            model_name='tafzily',
            name='postalCode',
        ),
        migrations.RemoveField(
            model_name='tafzily',
            name='selectedOptions',
        ),
        migrations.RemoveField(
            model_name='tafzily',
            name='subscription',
        ),
        migrations.RemoveField(
            model_name='tafzily',
            name='tafzily_sharh',
        ),
        migrations.RemoveField(
            model_name='tafzily',
            name='title',
        ),
        migrations.AddField(
            model_name='tafzily',
            name='allcode',
            field=models.CharField(blank=True, db_column='AllCode', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tafzily',
            name='atabarok',
            field=models.BooleanField(blank=True, db_column='Atabarok', null=True),
        ),
        migrations.AddField(
            model_name='tafzily',
            name='moencode',
            field=models.CharField(blank=True, db_column='MoenCode', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tafzily',
            name='moenname',
            field=models.CharField(blank=True, db_column='MoenName', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tafzily',
            name='tafzilysharh',
            field=models.CharField(blank=True, db_column='TafzilySharh', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tafzily',
            name='ashxas',
            field=models.CharField(blank=True, db_column='Ashxas', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tafzily',
            name='atbar',
            field=models.DecimalField(blank=True, db_column='Atbar', decimal_places=4, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='tafzily',
            name='bad',
            field=models.DecimalField(blank=True, db_column='Bad', decimal_places=4, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='tafzily',
            name='change',
            field=models.DecimalField(blank=True, db_column='Change', decimal_places=4, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='tafzily',
            name='city',
            field=models.CharField(blank=True, db_column='City', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tafzily',
            name='daftar',
            field=models.CharField(blank=True, db_column='Daftar', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tafzily',
            name='fname',
            field=models.CharField(blank=True, db_column='Fname', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tafzily',
            name='lastname',
            field=models.CharField(blank=True, db_column='Lastname', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tafzily',
            name='mandeh',
            field=models.DecimalField(blank=True, db_column='Mandeh', decimal_places=4, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='tafzily',
            name='moarref',
            field=models.CharField(blank=True, db_column='Moarref', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tafzily',
            name='ozv',
            field=models.BooleanField(blank=True, db_column='Ozv', null=True),
        ),
        migrations.AlterField(
            model_name='tafzily',
            name='sms',
            field=models.CharField(blank=True, db_column='SMS', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tafzily',
            name='tafzilycode',
            field=models.DecimalField(blank=True, db_column='TafzilyCode', decimal_places=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='tafzily',
            name='tel',
            field=models.CharField(blank=True, db_column='Tel', max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name='tafzily',
            table='Tafzily',
        ),
    ]
