# Generated by Django 5.2.4 on 2025-09-07 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tafzili', '0002_alter_tafzily_options_remove_tafzily_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tafzily',
            options={'managed': False},
        ),
    ]
