from django.db import models

class Kala(models.Model):
    Code = models.CharField(max_length=50, primary_key=True)
    Name = models.CharField(max_length=255)
    Qc = models.CharField(max_length=50, blank=True, null=True)
    MoenCode = models.CharField(max_length=50, blank=True, null=True)
    MoenName = models.CharField(max_length=255, blank=True, null=True)
    Point = models.IntegerField(blank=True, null=True)
    PriceKind = models.CharField(max_length=50, blank=True, null=True)
    MainUnit = models.CharField(max_length=50, blank=True, null=True)
    SlaveUnit = models.CharField(max_length=50, blank=True, null=True)
    Mbna = models.CharField(max_length=50, blank=True, null=True)
    AllT = models.CharField(max_length=50, blank=True, null=True)
    Price = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True, default=0)
    Percent = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    Vaz = models.CharField(max_length=50, blank=True, null=True)
    PriceF = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    KindP = models.CharField(max_length=50, blank=True, null=True)
    ID_F = models.IntegerField(blank=True, null=True)
    NN = models.CharField(max_length=50, blank=True, null=True)
    BarCode = models.CharField(max_length=50, blank=True, null=True)
    bar = models.CharField(max_length=50, blank=True, null=True)
    kind = models.CharField(max_length=50, blank=True, null=True)
    GROUPK = models.CharField(max_length=50, blank=True, null=True)
    NUMGK = models.IntegerField(blank=True, null=True)
    kindN = models.CharField(max_length=50, blank=True, null=True)
    Tax1 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    Tax2 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    Tax = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    Dis = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    barcode1 = models.CharField(max_length=50, blank=True, null=True)
    barcode2 = models.CharField(max_length=50, blank=True, null=True)
    shomareh = models.CharField(max_length=50, blank=True, null=True)
    Price1 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    Price2 = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    AllSales = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    Arz = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    Bar2 = models.CharField(max_length=50, blank=True, null=True)
    barcode3 = models.CharField(max_length=50, blank=True, null=True)
    barcode4 = models.CharField(max_length=50, blank=True, null=True)
    barcode5 = models.CharField(max_length=50, blank=True, null=True)
    barcode6 = models.CharField(max_length=50, blank=True, null=True)
    Jayezeh = models.CharField(max_length=50, blank=True, null=True)
    Mojode = models.DecimalField(max_digits=20, decimal_places=2, blank=True, null=True, default=0)
    tafcode = models.CharField(max_length=50, blank=True, null=True)
    tafName = models.CharField(max_length=255, blank=True, null=True)
    Tol = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)
    Zexamat = models.DecimalField(max_digits=18, decimal_places=2, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'Kala'
        
        